import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";
import CustomProviders from "./Provider";
import LogoMain from '@/src/assets/images/logo_main.png';
import Toast from "@/components/Toast";
import DefaultLayout from "@/components/Layout";
import { GoogleOAuthProvider } from '@react-oauth/google';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
  themeColor: '#FFFFFF',
  icons: [{ rel: 'icon', url: LogoMain.src },
  { rel: 'icon', type: 'image/png', sizes: "32x32", url: "/favicon-32x32.png" },
  { rel: 'icon', type: 'image/png', sizes: "16x16", url: "/favicon-16x16.png" }],
  robots: {
    googleBot: process.env.NEXT_PUBLIC_BASE_URL
  },
  alternates: {
    canonical: process.env.NEXT_PUBLIC_BASE_URL
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
      <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
      <meta name="apple-mobile-web-app-title" content="Main Shop" />
      <meta name="application-name" content="Main Shop" />
      <meta name="msapplication-TileColor" content="#603cba" />
      <link rel="manifest" href="/manifest.json" />
      <ThemeRegistry options={{ key: "mui" }}>
        <body className={inter.className} suppressHydrationWarning={true}>
          <CustomProviders>
            <DefaultLayout>
              {children}
            </DefaultLayout>
            <Toast />
          </CustomProviders>
        </body>
      </ThemeRegistry>
    </html>
  );
}
