import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";
import { getServerSession } from "next-auth";
import CustomProviders from "./Provider";
import { authOptions } from "./api/auth/options";
import { themeColor } from "@/utils/themeColor";
import LogoMain from '@/src/assets/images/logo_main.png';
import Toast from "@/components/Toast";
import AppBarUI from "@/components/AppBar";
import DefaultLayout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
  themeColor: themeColor.PRIMARY_COLOR,
  icons: [{ rel: 'icon', url: LogoMain.src }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <ThemeRegistry options={{ key: "mui" }}>
        <body className={inter.className}>
          <CustomProviders>
            <DefaultLayout>
              {children}
            </DefaultLayout>
            <Toast />
          </CustomProviders>
        </body>
      </ThemeRegistry>
    </html>
  );
}
