import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";
import { getServerSession } from "next-auth";
import CustomProviders from "./Provider";
import { authOptions } from "./api/auth/options";
import { themeColor } from "@/utils/themeColor";
import LogoMain from '@/src/assets/images/logo_main.png';
import Toast from "@/components/Toast";
import AppBarUI from "@/components/AppBar";
import DefaultLayout from "@/components/Layout";
import { redirect, usePathname } from "next/navigation";
import { headers } from 'next/headers';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
  themeColor: themeColor.PRIMARY_COLOR,
  icons: [{ rel: 'icon', url: LogoMain.src }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const headersList = headers();
  // const referer = headersList.get("referer");
  // const pathname = referer?.replace(`${process.env.NEXTAUTH_URL}`, '')
  // console.log("PATHNAME",);
  // const session = await getServerSession(authOptions);
  // console.log(`🚀 ~ file: layout.tsx ~ line 35 ~ session`, session)
  // if (!session && pathname !== '/signin') {
  //   redirect('/signin')
  // } else if (session && pathname === '/signin') {
  //   redirect('/')
  // }

  return (
    <html lang="en">
      <ThemeRegistry options={{ key: "mui" }}>
        <body className={inter.className}>
          <CustomProviders>
            <DefaultLayout>
              {children}
            </DefaultLayout>
            <Toast />
          </CustomProviders>
        </body>
      </ThemeRegistry>
    </html>
  );
}
